services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brain_test_agg_app
    depends_on:
      - database
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://username:password@database:5432/brain-ag-test?schema=public
      - PORT=3001

  database:
    image: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=brain-ag-test
    ports:
      - "5432:5432"
