frameworkVersion: "^3"
service: brain-ag-test

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64

custom:
  version: 'v1'
  serverless-offline:
    useChildProcesses: true
    httpPort: 3001
    lambdaPort: 3002

package:
  individually: true

functions:
  - ${file(./serverless.func.yml)}
